[package]
name = "dear_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26"

[dev-dependencies]
eframe = "0.26.0"
egui_demo_lib = "0.26.0"
